version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis:6379
      - REDIS_CHANNELS=market-events,code-events,flight-events
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MAX_RETRIES=3
      - RETRY_DELAY=1000
      - LOG_LEVEL=INFO
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - inflight-network
    volumes:
      - ./.env:/app/.env
    command: ["deno", "run", "--allow-net", "--allow-env", "--import-map=import_map.json", "src/main.ts"]

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - inflight-network
    command: redis-server --appendonly yes

networks:
  inflight-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
